Demo: Grab_Asynchronous.cpp
	g++ -g -o Grab_Asynchronous Grab_Asynchronous.cpp -I../../../include -Wl,-rpath=$(MVCAM_COMMON_RUNENV)/64 -L$(MVCAM_COMMON_RUNENV)/64 -lMvCameraControl -lpthread -std=c++11
	

clean:
	rm Grab_Asynchronous -rf
