Demo: InterfaceAndDeviceDemo.cpp
	g++ -g -o InterfaceAndDeviceDemo InterfaceAndDeviceDemo.cpp -I../../../include -Wl,-rpath=$(MVCAM_COMMON_RUNENV)/64 -L$(MVCAM_COMMON_RUNENV)/64 -lMvCameraControl -lpthread
	

clean:
	rm InterfaceAndDeviceDemo -rf
