Demo: ImageProcess.cpp
	g++ -g -o ImageProcess ImageProcess.cpp -I../../../include -Wl,-rpath=$(MVCAM_COMMON_RUNENV)/aarch64 -L$(MVCAM_COMMON_RUNENV)/aarch64 -lMvCameraControl 
	

clean:
	rm ImageProcess -rf
