Demo: HighBandwithDecode.cpp
	g++ -g -o HighBandwithDecode HighBandwithDecode.cpp -I../../../include -Wl,-rpath=$(MVCAM_COMMON_RUNENV)/64 -L$(MVCAM_COMMON_RUNENV)/64 -lMvCameraControl -lpthread
	

clean:
	rm HighBandwithDecode -rf