Demo: GrabImage_HighPerformance.cpp
	g++ -g -o GrabImage_HighPerformance GrabImage_HighPerformance.cpp -I../../../include -Wl,-rpath=$(MVCAM_COMMON_RUNENV)/aarch64 -L$(MVCAM_COMMON_RUNENV)/aarch64 -lMvCameraControl -lpthread 
	

clean:
	rm GrabImage_HighPerformance -rf
