# -*- coding: utf-8 -*-
# generated by 'xml2py'
# flags '-c -d -v C:\test_h\CameraParams.xml -o CameraParams_header.py'
from ctypes import *
import importlib
import sys
# CameraParams_const = importlib.import_module("MVS.Samples.64.Python.MvImport.CameraParams_const")
sys.path.append("MVS/Samples/64/Python/MvImport")

from CameraParams_const import *

STRING = c_char_p

MV_PointCloudFile_Undefined = 0                  # < \~chinese 未定义的点云格式                  \~english Undefined point cloud format
MV_EXPOSURE_MODE_TRIGGER_WIDTH = 1
MV_TRIGGER_SOURCE_FrequencyConverter = 8
MV_TRIGGER_SOURCE_SOFTWARE = 7
MV_TRIGGER_SOURCE_COUNTER0 = 4
MV_BALANCEWHITE_AUTO_OFF = 0
MV_TRIGGER_SOURCE_LINE3 = 3
MV_TRIGGER_SOURCE_LINE2 = 2
MV_TRIGGER_SOURCE_LINE1 = 1
MV_EXPOSURE_MODE_TIMED = 0
MV_TRIGGER_SOURCE_LINE0 = 0
AM_NA = 1
PixelType_Gvsp_BayerGR8 = 17301512
PixelType_Gvsp_Mono16 = 17825799
PixelType_Gvsp_Mono14 = 17825829
PixelType_Gvsp_Mono12 = 17825797
PixelType_Gvsp_Mono10 = 17825795
V_Undefined = 99
PixelType_Gvsp_Mono12_Packed = 17563654
V_Invisible = 3
PixelType_Gvsp_Mono8 = 17301505
V_Guru = 2
PixelType_Gvsp_Mono4p = 17039417
V_Expert = 1
PixelType_Gvsp_BayerGR16 = 17825838
PixelType_Gvsp_Mono1p = 16842807
PixelType_Gvsp_Undefined = -1
MV_GAIN_MODE_CONTINUOUS = 2
IFT_IString = 6
PixelType_Gvsp_BayerBG10 = 17825807
MV_ACQ_MODE_CONTINUOUS = 2
MV_EXPOSURE_AUTO_MODE_ONCE = 1
MV_Image_Png = 3
MV_Image_Jpeg = 2
MV_Image_Bmp = 1
MV_ACQ_MODE_MUTLI = 1
MV_EXPOSURE_AUTO_MODE_OFF = 0
PixelType_Gvsp_Jpeg = -2145910783
PixelType_Gvsp_RGB16_Planar = 36700196
IFT_IPort = 11
IFT_IEnumEntry = 10
IFT_ICategory = 8
IFT_IRegister = 7
IFT_IFloat = 5
IFT_IEnumeration = 9
IFT_ICommand = 4
IFT_IBoolean = 3
IFT_IInteger = 2
IFT_IBase = 1
PixelType_Gvsp_COORD3D_DEPTH_PLUS_MASK = -2112094207
IFT_IValue = 0
PixelType_Gvsp_Coord3D_AC32f = 36176066
PixelType_Gvsp_Coord3D_ABC32f_Planar = 39846081
PixelType_Gvsp_Coord3D_ABC32f = 39846080
PixelType_Gvsp_RGB12_Planar = 36700195
PixelType_Gvsp_RGB10_Planar = 36700194
PixelType_Gvsp_YCBCR709_411_8_CBYYCRYY = 34340930
MV_TRIGGER_MODE_OFF = 0
PixelType_Gvsp_YCBCR709_422_8_CBYCRY = 34603077
PixelType_Gvsp_YCBCR709_8_CBYCR = 35127360
PixelType_Gvsp_YCBCR709_422_8 = 34603073
PixelType_Gvsp_YCBCR601_411_8_CBYYCRYY = 34340927
PixelType_Gvsp_YCBCR601_422_8 = 34603070
PixelType_Gvsp_YCBCR601_8_CBYCR = 35127357
MV_TRIGGER_MODE_ON = 1
PixelType_Gvsp_YCBCR411_8_CBYYCRYY = 34340924
PixelType_Gvsp_YCBCR422_8_CBYCRY = 34603075
PixelType_Gvsp_YCBCR422_8 = 34603067
PixelType_Gvsp_YCBCR8_CBYCR = 35127354
PixelType_Gvsp_YUV444_Packed = 35127328
PixelType_Gvsp_YUV422_YUYV_Packed = 34603058
PixelType_Gvsp_YUV422_Packed = 34603039
PixelType_Gvsp_YUV411_Packed = 34340894
PixelType_Gvsp_BGR565_Packed = 34603062
PixelType_Gvsp_RGB565_Packed = 34603061
PixelType_Gvsp_RGB12V1_Packed = 35913780
PixelType_Gvsp_RGB10V2_Packed = 35651613
PixelType_Gvsp_RGB16_Packed = 36700211
PixelType_Gvsp_YCBCR601_422_8_CBYCRY = 34603076
PixelType_Gvsp_RGB12_Packed = 36700186
PixelType_Gvsp_BGR10_Packed = 36700185
MV_GIGE_TRANSTYPE_UNICAST = 0
PixelType_Gvsp_RGB10_Packed = 36700184
PixelType_Gvsp_BGRA8_Packed = 35651607
PixelType_Gvsp_RGBA8_Packed = 35651606
PixelType_Gvsp_BGR8_Packed = 35127317
PixelType_Gvsp_RGB8_Packed = 35127316
PixelType_Gvsp_BayerBG16 = 17825841
PixelType_Gvsp_BayerGB16 = 17825840
PixelType_Gvsp_BayerRG16 = 17825839
PixelType_Gvsp_BayerBG12_Packed = 17563693
PixelType_Gvsp_BayerGB12_Packed = 17563692
PixelType_Gvsp_BayerRG12_Packed = 17563691
PixelType_Gvsp_BayerGR12_Packed = 17563690
PixelType_Gvsp_BayerBG10_Packed = 17563689
PixelType_Gvsp_BayerGB10_Packed = 17563688
MV_GAIN_MODE_ONCE = 1
PixelType_Gvsp_BayerRG10_Packed = 17563687
PixelType_Gvsp_BayerGR10_Packed = 17563686
PixelType_Gvsp_BayerBG12 = 17825811
PixelType_Gvsp_BayerGB12 = 17825810
PixelType_Gvsp_BayerRG12 = 17825809
PixelType_Gvsp_BayerGR12 = 17825808
PixelType_Gvsp_BayerGB10 = 17825806
PixelType_Gvsp_BayerRG10 = 17825805
PixelType_Gvsp_BayerGR10 = 17825804
PixelType_Gvsp_BayerBG8 = 17301515
PixelType_Gvsp_BayerGB8 = 17301514
PixelType_Gvsp_BayerRG8 = 17301513
MV_EXPOSURE_AUTO_MODE_CONTINUOUS = 2
MV_Image_Tif = 4
AM_RW = 4
MV_BALANCEWHITE_AUTO_CONTINUOUS = 1
MV_BALANCEWHITE_AUTO_ONCE = 2
PixelType_Gvsp_Mono2p = 16908344
MV_GAMMA_SELECTOR_SRGB = 2
MV_GAIN_MODE_OFF = 0
PixelType_Gvsp_Mono10_Packed = 17563652
MV_GAMMA_SELECTOR_USER = 1
PixelType_Gvsp_RGB8_Planar = 35127329
PixelType_Gvsp_Mono8_Signed = 17301506
MV_GrabStrategy_UpcomingImage = 3                # < \~chinese 等待下一帧图像                     \~english Wait for the next image
MV_GrabStrategy_LatestImages = 2                 # < \~chinese 获取列表中最新的图像               \~english Gets the latest image in the list
MV_GrabStrategy_LatestImagesOnly = 1             # < \~chinese 获取列表中最新的一帧图像（同时清除列表中的其余图像）         \~english Gets the most recent image in the list (while clearing the rest of the images in the list)
MV_GrabStrategy_OneByOne = 0                     # < \~chinese 从旧到新一帧一帧的获取图像        \~english Frame by frame from old to new
MV_PointCloudFile_OBJ = 3                        # < \~chinese OBJ点云格式                       \~english The point cloud format named OBJ
MV_PointCloudFile_CSV = 2                        # < \~chinese CSV点云格式                       \~english The point cloud format named CSV
MV_PointCloudFile_PLY = 1                        # < \~chinese PLY点云格式                       \~english The point cloud format named PLY
MV_ACQ_MODE_SINGLE = 0
AM_CycleDetect = 6
MV_GIGE_TRANSTYPE_MULTICAST_WITHOUT_RECV = 65537
AM_Undefined = 5
MV_GIGE_TRANSTYPE_UNICAST_WITHOUT_RECV = 65536
MV_GIGE_TRANSTYPE_UNICAST_DEFINED_PORT = 5
AM_RO = 3
MV_GIGE_TRANSTYPE_SUBNETBROADCAST = 3
PixelType_Gvsp_RGB10V1_Packed = 35651612
MV_GIGE_TRANSTYPE_LIMITEDBROADCAST = 2
MV_GIGE_TRANSTYPE_MULTICAST = 1
MV_GIGE_TRANSTYPE_CAMERADEFINED = 4
AM_NI = 0
PixelType_Gvsp_BGR12_Packed = 36700187
MV_Image_Undefined = 0
AM_WO = 2
MV_FormatType_AVI = 1                            # < \~chinese AVI视频格式                     \~english AVI format type
MV_FormatType_Undefined = 0                      # < \~chinese 未定义的格式类型                  \~english Undefined format type
SortMethod_SerialNumber = 0                      # < \~chinese 按序列号排序                     \~english Sorting by SerialNumber
SortMethod_UserID = 1                            # < \~chinese 按用户自定义名字排序             \~english Sorting by UserID
SortMethod_CurrentIP_ASC = 2                     # < \~chinese 按当前IP地址排序（升序）         \~english Sorting by current IP（Ascending）
SortMethod_CurrentIP_DESC = 3                    # < \~chinese 按当前IP地址排序（降序）         \~english Sorting by current IP（Descending）
MV_IMAGE_ROTATE_90 = 1                           # < \~chinese 旋转90度         \~english Rotate 90 degrees
MV_IMAGE_ROTATE_180 = 2                          # < \~chinese 旋转180度         \~english Rotate 180 degrees
MV_IMAGE_ROTATE_270 = 3                          # < \~chinese 旋转270度         \~english Rotate 270 degrees
MV_FLIP_VERTICAL = 1                             # < \~chinese 垂直翻转          \~english flip vertical
MV_FLIP_HORIZONTAL = 2                           # < \~chinese 旋水平翻转         \~english flip horizontal
MV_CC_GAMMA_TYPE_NONE = 0                        # < \~chinese 不启用                       \~english Disable
MV_CC_GAMMA_TYPE_VALUE = 1                       # < \~chinese Gamma值                      \~english Gamma value
MV_CC_GAMMA_TYPE_USER_CURVE = 2                  # < \~chinese Gamma曲线                    \~english Gamma curve
MV_CC_GAMMA_TYPE_LRGB2SRGB = 3                   # < \~chinese linear RGB to sRGB           \~english linear RGB to sRGB
MV_CC_GAMMA_TYPE_SRGB2LRGB = 4                   # < \~chinese sRGB to linear RGB(仅色彩插值时支持，色彩校正时无效) \~english sRGB to linear RGB
MV_CC_STREAM_EXCEPTION_ABNORMAL_IMAGE = 0x4001   # < \~chinese 异常的图像，该帧被丢弃            \~english abnormal image,the frame is discarded
MV_CC_STREAM_EXCEPTION_LIST_OVERFLOW = 0x4002    # < \~chinese 缓存列表溢出，清除最旧的一帧       \~english Cache list overflow, clear the oldest frame
MV_CC_STREAM_EXCEPTION_LIST_EMPTY = 0x4003       # < \~chinese 缓存列表为空，该帧被丢弃           \~english Cache list is empty,the frame is discarded
MV_CC_STREAM_EXCEPTION_RECONNECTION = 0x4004    # < \~chinese 断流恢复                         \~english reconnect
MV_CC_STREAM_EXCEPTION_DISCONNECTED = 0x4005    # < \~chinese 断流,恢复失败,取流被中止    \~english reconnect fail, stream is  terminated
MV_CC_STREAM_EXCEPTION_DEVICE = 0x4006          # < \~chinese 设备异常,取流被中止         \~english device exception
MV_SPLIT_BY_LINE = 1                            #< \~chinese 源图像按行拆分成多张图像         \~english Source image split into multiple images by line
V_Beginner = 0
int8_t = c_int8
int16_t = c_int16
int32_t = c_int32
int64_t = c_int64
uint8_t = c_uint8
uint16_t = c_uint16
uint32_t = c_uint32
uint64_t = c_uint64
int_least8_t = c_byte
int_least16_t = c_short
int_least32_t = c_int
int_least64_t = c_long
uint_least8_t = c_ubyte
uint_least16_t = c_ushort
uint_least32_t = c_uint
uint_least64_t = c_ulong
int_fast8_t = c_byte
int_fast16_t = c_long
int_fast32_t = c_long
int_fast64_t = c_long
uint_fast8_t = c_ubyte
uint_fast16_t = c_ulong
uint_fast32_t = c_ulong
uint_fast64_t = c_ulong
intptr_t = c_long
uintptr_t = c_ulong
intmax_t = c_long
uintmax_t = c_ulong
# CameraParams.h 21
class _MV_GIGE_DEVICE_INFO_(Structure):
    pass
_MV_GIGE_DEVICE_INFO_._fields_ = [
    # CameraParams.h 21
    ('nIpCfgOption', c_uint),
    ('nIpCfgCurrent', c_uint),
    ('nCurrentIp', c_uint),
    ('nCurrentSubNetMask', c_uint),
    ('nDefultGateWay', c_uint),
    ('chManufacturerName', c_ubyte * 32),
    ('chModelName', c_ubyte * 32),
    ('chDeviceVersion', c_ubyte * 32),
    ('chManufacturerSpecificInfo', c_ubyte * 48),
    ('chSerialNumber', c_ubyte * 16),
    ('chUserDefinedName', c_ubyte * 16),
    ('nNetExport', c_uint),
    ('nReserved', c_uint * 4),
]
MV_GIGE_DEVICE_INFO = _MV_GIGE_DEVICE_INFO_
# CameraParams.h 42
class _MV_USB3_DEVICE_INFO_(Structure):
    pass
_MV_USB3_DEVICE_INFO_._fields_ = [
    # CameraParams.h 42
    ('CrtlInEndPoint', c_ubyte),
    ('CrtlOutEndPoint', c_ubyte),
    ('StreamEndPoint', c_ubyte),
    ('EventEndPoint', c_ubyte),
    ('idVendor', c_ushort),
    ('idProduct', c_ushort),
    ('nDeviceNumber', c_uint),
    ('chDeviceGUID', c_ubyte * 64),
    ('chVendorName', c_ubyte * 64),
    ('chModelName', c_ubyte * 64),
    ('chFamilyName', c_ubyte * 64),
    ('chDeviceVersion', c_ubyte * 64),
    ('chManufacturerName', c_ubyte * 64),
    ('chSerialNumber', c_ubyte * 64),
    ('chUserDefinedName', c_ubyte * 64),
    ('nbcdUSB', c_uint),
    ('nReserved', c_uint * 3),
]
MV_USB3_DEVICE_INFO = _MV_USB3_DEVICE_INFO_

# CameraLink设备信息    \~english CameraLink device info
class _MV_CamL_DEV_INFO_(Structure):
    pass
_MV_CamL_DEV_INFO_._fields_ = [
    ('chPortID', c_ubyte * INFO_MAX_BUFFER_SIZE),           # < \~chinese 端口号            \~english Port ID         
    ('chModelName', c_ubyte * INFO_MAX_BUFFER_SIZE),        # < \~chinese 设备型号          \~english Model name
    ('chFamilyName', c_ubyte * INFO_MAX_BUFFER_SIZE),       # < \~chinese 家族名字          \~english Family Name
    ('chDeviceVersion', c_ubyte * INFO_MAX_BUFFER_SIZE),    # < \~chinese 设备版本号        \~english Device Version
    ('chManufacturerName', c_ubyte * INFO_MAX_BUFFER_SIZE), # < \~chinese 制造商名字        \~english Manufacturer Name
    ('chSerialNumber', c_ubyte * INFO_MAX_BUFFER_SIZE),     # < \~chinese 序列号            \~english Serial Number
    ('nReserved', c_uint * 38),                             # < \~chinese 保留字节          \~english Reserved bytes
]
MV_CamL_DEV_INFO = _MV_CamL_DEV_INFO_

# CameraParams.h 64
class _MV_CC_DEVICE_INFO_(Structure):
    pass
# CameraParams.h 76
class N19_MV_CC_DEVICE_INFO_3DOT_0E(Union):
    pass
N19_MV_CC_DEVICE_INFO_3DOT_0E._fields_ = [
    # CameraParams.h 76
    ('stGigEInfo', MV_GIGE_DEVICE_INFO),
    ('stUsb3VInfo', MV_USB3_DEVICE_INFO),
    ('stCamLInfo', MV_CamL_DEV_INFO),                      # < \~chinese CamLink设备信息     \~english CamLink device information
]
_MV_CC_DEVICE_INFO_._fields_ = [
    # CameraParams.h 64
    ('nMajorVer', c_ushort),
    ('nMinorVer', c_ushort),
    ('nMacAddrHigh', c_uint),
    ('nMacAddrLow', c_uint),
    ('nTLayerType', c_uint),
    ('nReserved', c_uint * 4),
    ('SpecialInfo', N19_MV_CC_DEVICE_INFO_3DOT_0E),
]
MV_CC_DEVICE_INFO = _MV_CC_DEVICE_INFO_
# CameraParams.h 86
class _MV_NETTRANS_INFO_(Structure):
    pass
_MV_NETTRANS_INFO_._fields_ = [
    # CameraParams.h 86
    ('nReviceDataSize', int64_t),
    ('nThrowFrameCount', c_int),
    ('nNetRecvFrameCount', c_uint),         # < \~chinese 收到帧计数           \~english Receive Frame count
    ('nRequestResendPacketCount', int64_t), # < \~chinese 请求重发包数         \~english Request Resend Packet Count
    ('nResendPacketCount', int64_t),        # < \~chinese 重发包数            \~english Resend Packet Count
]
MV_NETTRANS_INFO = _MV_NETTRANS_INFO_
# CameraParams.h 101
class _MV_CC_DEVICE_INFO_LIST_(Structure):
    pass
_MV_CC_DEVICE_INFO_LIST_._fields_ = [
    # CameraParams.h 101
    ('nDeviceNum', c_uint),
    ('pDeviceInfo', POINTER(MV_CC_DEVICE_INFO) * 256),
]
MV_CC_DEVICE_INFO_LIST = _MV_CC_DEVICE_INFO_LIST_

# 通过GenTL枚举到的Interface信息    \~english Interface Information with GenTL
class _MV_GENTL_IF_INFO_(Structure):
    pass
_MV_GENTL_IF_INFO_._fields_ = [
    ('chInterfaceID', c_ubyte * INFO_MAX_BUFFER_SIZE), # < \~chinese GenTL接口ID        \~english Interface ID of GenTL
    ('chTLType', c_ubyte * INFO_MAX_BUFFER_SIZE),      # < \~chinese 传输层类型          \~english Transport Layer type
    ('chDisplayName', c_ubyte * INFO_MAX_BUFFER_SIZE), # < \~chinese 设备显示名称         \~english Display name
    ('nCtiIndex', c_uint),                             # < \~chinese GenTL的cti文件索引   \~english Cti file index of GenTL 
    ('nReserved', c_uint * 8),                         # < \~chinese 保留字节             \~english Reserved bytes
]
MV_GENTL_IF_INFO = _MV_GENTL_IF_INFO_

# 通过GenTL枚举到的设备信息列表    \~english Device Information List with GenTL
class _MV_GENTL_IF_INFO_LIST_(Structure):
    pass
_MV_GENTL_IF_INFO_LIST_._fields_ = [
    ('nInterfaceNum', c_uint),                                    # < \~chinese 在线设备数量         \~english Online Device Number
    ('pIFInfo', POINTER(MV_GENTL_IF_INFO) * MV_MAX_GENTL_IF_NUM), # < \~chinese 支持最多256个设备     \~english Support up to 256 devices
]
MV_GENTL_IF_INFO_LIST = _MV_GENTL_IF_INFO_LIST_

# 通过GenTL枚举到的设备信息    \~english Device Information with GenTL
class _MV_GENTL_DEV_INFO_(Structure):
    pass
_MV_GENTL_DEV_INFO_._fields_ = [
    ('chInterfaceID', c_ubyte * INFO_MAX_BUFFER_SIZE),          # < \~chinese GenTL接口ID         \~english Interface ID of GenTL
    ('chDeviceID', c_ubyte * INFO_MAX_BUFFER_SIZE),             # < \~chinese 设备ID              \~english Device ID
    ('chVendorName', c_ubyte * INFO_MAX_BUFFER_SIZE),           # < \~chinese 供应商名字          \~english Vendor Name
    ('chModelName', c_ubyte * INFO_MAX_BUFFER_SIZE),            # < \~chinese 型号名字            \~english Model name
    ('chTLType', c_ubyte * INFO_MAX_BUFFER_SIZE),               # < \~chinese 传输层类型          \~english Transport Layer type
    ('chDisplayName', c_ubyte * INFO_MAX_BUFFER_SIZE),          # < \~chinese 显示名称           \~english Display name
    ('chUserDefinedName', c_ubyte * INFO_MAX_BUFFER_SIZE),      # < \~chinese 用户自定义名字      \~english User defined name
    ('chSerialNumber', c_ubyte * INFO_MAX_BUFFER_SIZE),         # < \~chinese 序列号             \~english Serial number
    ('chDeviceVersion', c_ubyte * INFO_MAX_BUFFER_SIZE),        # < \~chinese 设备版本号         \~english Device version
    ('nCtiIndex', c_uint),                                      # < \~chinese cti索引            \~english Cti Index
    ('nReserved', c_uint * 8),                                  # < \~chinese 保留字节           \~english Reserved bytes
]
MV_GENTL_DEV_INFO = _MV_GENTL_DEV_INFO_

# 通过GenTL枚举到的设备信息列表    \~english Device Information List with GenTL
class _MV_GENTL_DEV_INFO_LIST_(Structure):
    pass
_MV_GENTL_DEV_INFO_LIST_._fields_ = [
    ('nDeviceNum', c_uint),                                             # < \~chinese 在线设备数量         \~english Online Device Number
    ('pDeviceInfo', POINTER(MV_GENTL_DEV_INFO) * MV_MAX_GENTL_DEV_NUM), # < \~chinese GenTL设备信息       \~english device infomation of GenTL device
]
MV_GENTL_DEV_INFO_LIST = _MV_GENTL_DEV_INFO_LIST_

# Chunk内容    \~english The content of ChunkData
class _MV_CHUNK_DATA_CONTENT_(Structure):
    pass
_MV_CHUNK_DATA_CONTENT_._fields_ = [
    ('pChunkData', POINTER(c_ubyte)),  # < \~chinese 块数据             \~english Chunk data
    ('nChunkID', c_uint),              # < \~chinese 块数据ID           \~english Chunk id
    ('nChunkLen', c_uint),             # < \~chinese 块数据长度         \~english Chunk len
    ('nReserved', c_uint * 8),         # < \~chinese 保留字节           \~english Reserved bytes
]
MV_CHUNK_DATA_CONTENT = _MV_CHUNK_DATA_CONTENT_

# CameraParams.h 110
class _MV_FRAME_OUT_INFO_(Structure):
    pass

# values for enumeration 'MvGvspPixelType'
MvGvspPixelType = int64_t # enum
_MV_FRAME_OUT_INFO_._fields_ = [
    # CameraParams.h 110
    ('nWidth', c_ushort),
    ('nHeight', c_ushort),
    ('enPixelType', MvGvspPixelType),
    ('nFrameNum', c_uint),
    ('nDevTimeStampHigh', c_uint),
    ('nDevTimeStampLow', c_uint),
    ('nReserved0', c_uint),
    ('nHostTimeStamp', int64_t),
    ('nFrameLen', c_uint),
    ('nLostPacket', c_uint),
    ('nReserved', c_uint * 2),
]
MV_FRAME_OUT_INFO = _MV_FRAME_OUT_INFO_
# CameraParams.h 129
class _MV_FRAME_OUT_INFO_EX_(Structure):
    pass

class N22_MV_FRAME_OUT_INFO_EX_3DOT_1E(Union):
    pass
N22_MV_FRAME_OUT_INFO_EX_3DOT_1E._fields_ = [
    ('pUnparsedChunkContent', POINTER(MV_CHUNK_DATA_CONTENT)), # < \~chinese Chunk内容         \~english Chunk Content
    ('nAligning', int64_t),                                    # < \~chinese 校准字段          \~english Aligning
]
_MV_FRAME_OUT_INFO_EX_._fields_ = [
    # CameraParams.h 129
    ('nWidth', c_ushort),
    ('nHeight', c_ushort),
    ('enPixelType', MvGvspPixelType),
    ('nFrameNum', c_uint),
    ('nDevTimeStampHigh', c_uint),
    ('nDevTimeStampLow', c_uint),
    ('nReserved0', c_uint),
    ('nHostTimeStamp', int64_t),
    ('nFrameLen', c_uint),
    ('nSecondCount', c_uint),
    ('nCycleCount', c_uint),
    ('nCycleOffset', c_uint),
    ('fGain', c_float),
    ('fExposureTime', c_float),
    ('nAverageBrightness', c_uint),
    ('nRed', c_uint),
    ('nGreen', c_uint),
    ('nBlue', c_uint),
    ('nFrameCounter', c_uint),
    ('nTriggerIndex', c_uint),
    ('nInput', c_uint),
    ('nOutput', c_uint),
    ('nOffsetX', c_ushort),
    ('nOffsetY', c_ushort),
    ('nChunkWidth', c_ushort),
    ('nChunkHeight', c_ushort),
    ('nLostPacket', c_uint),
    ('nUnparsedChunkNum', c_uint),                           # < \~chinese 未解析的Chunkdata个数 \~english Unparsed chunk number
    ('UnparsedChunkList', N22_MV_FRAME_OUT_INFO_EX_3DOT_1E), # < \~chinese 数据库链表            \~english Unparsed chunk list
    ('nExtendWidth', c_uint),                                # < \~chinese 图像宽(扩展变量)       \~english Image Width
    ('nExtendHeight', c_uint),                               # < \~chinese 图像高(扩展变量)       \~english Image Height
    ('nReserved', c_uint * 34),
]
MV_FRAME_OUT_INFO_EX = _MV_FRAME_OUT_INFO_EX_
# CameraParams.h 176
class _MV_DISPLAY_FRAME_INFO_(Structure):
    pass
_MV_DISPLAY_FRAME_INFO_._fields_ = [
    # CameraParams.h 176
    ('hWnd', c_void_p),
    ('pData', POINTER(c_ubyte)),
    ('nDataLen', c_uint),
    ('nWidth', c_ushort),
    ('nHeight', c_ushort),
    ('enPixelType', MvGvspPixelType),
    ('nRes', c_uint * 4),
]
MV_DISPLAY_FRAME_INFO = _MV_DISPLAY_FRAME_INFO_

# \~chinese 显示帧信息   \~english Display frame information
class _MV_DISPLAY_FRAME_INFO_EX_(Structure):
    pass
_MV_DISPLAY_FRAME_INFO_EX_._fields_ = [
    ('nWidth', c_uint),                # < \~chinese 图像宽    \~english Image Width
    ('nHeight', c_uint),               # < \~chinese 图像高    \~english Image Height
    ('enPixelType', MvGvspPixelType),  # < \~chinese 像素格式            \~english Pixel Type
    ('pImageBuf', POINTER(c_ubyte)),   # < \~chinese 输入图像缓存         \~english Input image buffer
    ('nImageBufLen', c_uint),          # < \~chinese 输入图像长度         \~english Input image length
    ('nRes', c_uint * 4),              # < \~chinese 保留字节            \~english Reserved bytes
]
MV_DISPLAY_FRAME_INFO_EX = _MV_DISPLAY_FRAME_INFO_EX_

# 图像结构体，输出图像指针地址及图像信息    \~english Image Struct, output the pointer of Image and the information of the specific image
class _MV_FRAME_OUT_(Structure):
    pass
_MV_FRAME_OUT_._fields_ = [
    ('pBufAddr', POINTER(c_ubyte)),         # < \~chinese 图像指针地址         \~english pointer of image
    ('stFrameInfo', MV_FRAME_OUT_INFO_EX),  # < \~chinese 图像信息            \~english information of the specific image
    ('nRes', c_uint * 16),                  # < \~chinese 保留字节            \~english Reserved bytes
]
MV_FRAME_OUT = _MV_FRAME_OUT_

# values for enumeration '_MV_GRAB_STRATEGY_'
_MV_GRAB_STRATEGY_ = c_int # enum       
MV_GRAB_STRATEGY = _MV_GRAB_STRATEGY_   

# values for enumeration 'MV_SAVE_POINT_CLOUD_FILE_TYPE'
MV_SAVE_POINT_CLOUD_FILE_TYPE = c_int # enum

# \~chinese 保存3D数据到缓存    \~english Save 3D data to buffer
class _MV_SAVE_POINT_CLOUD_PARAM_(Structure):
    pass
_MV_SAVE_POINT_CLOUD_PARAM_._fields_ = [
    ('nLinePntNum', c_uint),                                 # < \~chinese 每一行点的数量，即图像宽                                             \~english The number of points in each row,which is the width of the image
    ('nLineNum', c_uint),                                    # < \~chinese 行数，即图像高                                                       \~english The number of rows,which is the height of the image
    ('enSrcPixelType', MvGvspPixelType),                     # < \~chinese 输入数据的像素格式                                                    \~english The pixel format of the input data
    ('pSrcData', POINTER(c_ubyte)),                          # < \~chinese 输入数据缓存                                                          \~english Input data buffer
    ('nSrcDataLen', c_uint),                                 # < \~chinese 输入数据大小                                                           \~english Input data size
    ('pDstBuf', POINTER(c_ubyte)),                           # < \~chinese 输出像素数据缓存                                                        \~english Output pixel data buffer
    ('nDstBufSize', c_uint),                                 # < \~chinese 提供的输出缓冲区大小(nLinePntNum * nLineNum * (16*3 + 4) + 2048)         \~english Output buffer size provided (nLinePntNum * nLineNum * (16*3 + 4) + 2048) 
    ('nDstBufLen', c_uint),                                  # < \~chinese 输出像素数据缓存长度                                                     \~english Output pixel data buffer size
    ('enPointCloudFileType', MV_SAVE_POINT_CLOUD_FILE_TYPE), # < \~chinese 提供输出的点云文件类型                                                    \~english Output point data file type provided
    ('nReserved', c_uint * 8),                               # < \~chinese 保留字节                                                                 \~english Reserved bytes
]
MV_SAVE_POINT_CLOUD_PARAM = _MV_SAVE_POINT_CLOUD_PARAM_

# values for enumeration 'MV_SAVE_IAMGE_TYPE'
MV_SAVE_IAMGE_TYPE = c_int # enum
# CameraParams.h 198
class _MV_SAVE_IMAGE_PARAM_T_(Structure):
    pass
_MV_SAVE_IMAGE_PARAM_T_._fields_ = [
    # CameraParams.h 198
    ('pData', POINTER(c_ubyte)),
    ('nDataLen', c_uint),
    ('enPixelType', MvGvspPixelType),
    ('nWidth', c_ushort),
    ('nHeight', c_ushort),
    ('pImageBuffer', POINTER(c_ubyte)),
    ('nImageLen', c_uint),
    ('nBufferSize', c_uint),
    ('enImageType', MV_SAVE_IAMGE_TYPE),
]
MV_SAVE_IMAGE_PARAM = _MV_SAVE_IMAGE_PARAM_T_
# CameraParams.h 214
class _MV_SAVE_IMAGE_PARAM_T_EX_(Structure):
    pass
_MV_SAVE_IMAGE_PARAM_T_EX_._fields_ = [
    # CameraParams.h 214
    ('pData', POINTER(c_ubyte)),
    ('nDataLen', c_uint),
    ('enPixelType', MvGvspPixelType),
    ('nWidth', c_ushort),
    ('nHeight', c_ushort),
    ('pImageBuffer', POINTER(c_ubyte)),
    ('nImageLen', c_uint),
    ('nBufferSize', c_uint),
    ('enImageType', MV_SAVE_IAMGE_TYPE),
    ('nJpgQuality', c_uint),
    ('iMethodValue', c_uint),
    ('nReserved', c_uint * 3),
]
MV_SAVE_IMAGE_PARAM_EX = _MV_SAVE_IMAGE_PARAM_T_EX_

# CameraParams.h 236
class _MV_PIXEL_CONVERT_PARAM_T_(Structure):
    pass
_MV_PIXEL_CONVERT_PARAM_T_._fields_ = [
    # CameraParams.h 236
    ('nWidth', c_ushort),
    ('nHeight', c_ushort),
    ('enSrcPixelType', MvGvspPixelType),
    ('pSrcData', POINTER(c_ubyte)),
    ('nSrcDataLen', c_uint),
    ('enDstPixelType', MvGvspPixelType),
    ('pDstBuffer', POINTER(c_ubyte)),
    ('nDstLen', c_uint),
    ('nDstBufferSize', c_uint),
    ('nRes', c_uint * 4),
]
MV_CC_PIXEL_CONVERT_PARAM = _MV_PIXEL_CONVERT_PARAM_T_

# values for enumeration '_MV_RECORD_FORMAT_TYPE_'
_MV_RECORD_FORMAT_TYPE_ = c_int # enum
MV_RECORD_FORMAT_TYPE = _MV_RECORD_FORMAT_TYPE_

# \~chinese 录像参数    \~english Record Parameters
class _MV_CC_RECORD_PARAM_T_(Structure):
    pass
_MV_CC_RECORD_PARAM_T_._fields_ = [
    ('enPixelType', MvGvspPixelType),           # < \~chinese 输入数据的像素格式                                \~english Ip config option
    ('nWidth', c_ushort),                       # < \~chinese 图像宽(指定目标参数时需为2的倍数)                   \~english Ip config option
    ('nHeight', c_ushort),                      # < \~chinese 图像高(指定目标参数时需为2的倍数)                    \~english Ip config option
    ('fFrameRate', c_float),                    # < \~chinese 帧率fps(1/16-120)                                  \~english Ip config option
    ('nBitRate', c_uint),                       # < \~chinese 码率kbps(128kbps-16Mbps)                            \~english Ip config option
    ('enRecordFmtType', MV_RECORD_FORMAT_TYPE), # < \~chinese 录像格式                                              \~english Ip config option
    ('strFilePath', STRING),                    # < \~chinese 录像文件存放路径(如果路径中存在中文，需转成utf-8)         \~english Video file storage path (if there is Chinese in the path, it needs to be converted to utf-8)
    ('nRes', c_uint * 8),                       # < \~chinese 保留字节                                                \~english Reserved bytes
]
MV_CC_RECORD_PARAM = _MV_CC_RECORD_PARAM_T_

# \~chinese 录像数据    \~english Record Data
class _MV_CC_INPUT_FRAME_INFO_T_(Structure):
    pass
_MV_CC_INPUT_FRAME_INFO_T_._fields_ = [
    ('pData', POINTER(c_ubyte)),  # < \~chinese 图像数据指针         \~english Input Data Buffer
    ('nDataLen', c_uint),         # < \~chinese  输入数据大小         \~english Input Data Size
    ('nRes', c_uint * 8),         # < \~chinese 保留字节               \~english Reserved bytes
]
MV_CC_INPUT_FRAME_INFO = _MV_CC_INPUT_FRAME_INFO_T_

# values for enumeration '_MV_CAM_ACQUISITION_MODE_'
_MV_CAM_ACQUISITION_MODE_ = c_int # enum
MV_CAM_ACQUISITION_MODE = _MV_CAM_ACQUISITION_MODE_

# values for enumeration '_MV_CAM_GAIN_MODE_'
_MV_CAM_GAIN_MODE_ = c_int # enum
MV_CAM_GAIN_MODE = _MV_CAM_GAIN_MODE_

# values for enumeration '_MV_CAM_EXPOSURE_MODE_'
_MV_CAM_EXPOSURE_MODE_ = c_int # enum
MV_CAM_EXPOSURE_MODE = _MV_CAM_EXPOSURE_MODE_

# values for enumeration '_MV_CAM_EXPOSURE_AUTO_MODE_'
_MV_CAM_EXPOSURE_AUTO_MODE_ = c_int # enum
MV_CAM_EXPOSURE_AUTO_MODE = _MV_CAM_EXPOSURE_AUTO_MODE_

# values for enumeration '_MV_CAM_TRIGGER_MODE_'
_MV_CAM_TRIGGER_MODE_ = c_int # enum
MV_CAM_TRIGGER_MODE = _MV_CAM_TRIGGER_MODE_

# values for enumeration '_MV_CAM_GAMMA_SELECTOR_'
_MV_CAM_GAMMA_SELECTOR_ = c_int # enum
MV_CAM_GAMMA_SELECTOR = _MV_CAM_GAMMA_SELECTOR_

# values for enumeration '_MV_CAM_BALANCEWHITE_AUTO_'
_MV_CAM_BALANCEWHITE_AUTO_ = c_int # enum
MV_CAM_BALANCEWHITE_AUTO = _MV_CAM_BALANCEWHITE_AUTO_

# values for enumeration '_MV_CAM_TRIGGER_SOURCE_'
_MV_CAM_TRIGGER_SOURCE_ = c_int # enum
MV_CAM_TRIGGER_SOURCE = _MV_CAM_TRIGGER_SOURCE_

# values for enumeration '_MV_GIGE_TRANSMISSION_TYPE_'
_MV_GIGE_TRANSMISSION_TYPE_ = c_int # enum
MV_GIGE_TRANSMISSION_TYPE = _MV_GIGE_TRANSMISSION_TYPE_
# CameraParams.h 377
class _MV_ALL_MATCH_INFO_(Structure):
    pass
_MV_ALL_MATCH_INFO_._fields_ = [
    # CameraParams.h 377
    ('nType', c_uint),
    ('pInfo', c_void_p),
    ('nInfoSize', c_uint),
]
MV_ALL_MATCH_INFO = _MV_ALL_MATCH_INFO_
# CameraParams.h 387
class _MV_MATCH_INFO_NET_DETECT_(Structure):
    pass
_MV_MATCH_INFO_NET_DETECT_._fields_ = [
    # CameraParams.h 387
    ('nReviceDataSize', int64_t),
    ('nLostPacketCount', int64_t),
    ('nLostFrameCount', c_uint),
    ('nNetRecvFrameCount', c_uint),         # < \~chinese 收到帧计数           \~english Receive Frame count
    ('nRequestResendPacketCount', int64_t), # < \~chinese 请求重发包数         \~english Request Resend Packet Count
    ('nResendPacketCount', int64_t),        # < \~chinese 重发包数            \~english Resend Packet Count
]
MV_MATCH_INFO_NET_DETECT = _MV_MATCH_INFO_NET_DETECT_
# CameraParams.h 396
class _MV_MATCH_INFO_USB_DETECT_(Structure):
    pass
_MV_MATCH_INFO_USB_DETECT_._fields_ = [
    # CameraParams.h 396
    ('nReviceDataSize', int64_t),
    ('nRevicedFrameCount', c_uint),
    ('nErrorFrameCount', c_uint),
    ('nReserved', c_uint * 2),
]
MV_MATCH_INFO_USB_DETECT = _MV_MATCH_INFO_USB_DETECT_
# CameraParams.h 404
class _MV_IMAGE_BASIC_INFO_(Structure):
    pass
_MV_IMAGE_BASIC_INFO_._fields_ = [
    # CameraParams.h 404
    ('nWidthValue', c_ushort),
    ('nWidthMin', c_ushort),
    ('nWidthMax', c_uint),
    ('nWidthInc', c_uint),
    ('nHeightValue', c_uint),
    ('nHeightMin', c_uint),
    ('nHeightMax', c_uint),
    ('nHeightInc', c_uint),
    ('fFrameRateValue', c_float),
    ('fFrameRateMin', c_float),
    ('fFrameRateMax', c_float),
    ('enPixelType', c_uint),
    ('nSupportedPixelFmtNum', c_uint),
    ('enPixelList', c_uint * 64),
    ('nReserved', c_uint * 8),
]
MV_IMAGE_BASIC_INFO = _MV_IMAGE_BASIC_INFO_

# values for enumeration 'MV_XML_InterfaceType'
MV_XML_InterfaceType = c_int # enum

# values for enumeration 'MV_XML_AccessMode'
MV_XML_AccessMode = c_int # enum

# values for enumeration 'MV_XML_Visibility'
MV_XML_Visibility = c_int # enum
# CameraParams.h 500
class _MV_EVENT_OUT_INFO_(Structure):
    pass
_MV_EVENT_OUT_INFO_._fields_ = [
    # CameraParams.h 500
    ('EventName', c_char * 128),
    ('nEventID', c_ushort),
    ('nStreamChannel', c_ushort),
    ('nBlockIdHigh', c_uint),
    ('nBlockIdLow', c_uint),
    ('nTimestampHigh', c_uint),
    ('nTimestampLow', c_uint),
    ('pEventData', c_void_p),
    ('nEventDataSize', c_uint),
    ('nReserved', c_uint * 16),
]
MV_EVENT_OUT_INFO = _MV_EVENT_OUT_INFO_
# CameraParams.h 520
class _MV_CC_FILE_ACCESS_T(Structure):
    pass
_MV_CC_FILE_ACCESS_T._fields_ = [
    # CameraParams.h 520
    ('pUserFileName', STRING),
    ('pDevFileName', STRING),
    ('nReserved', c_uint * 32),
]
MV_CC_FILE_ACCESS = _MV_CC_FILE_ACCESS_T
# CameraParams.h 529
class _MV_CC_FILE_ACCESS_PROGRESS_T(Structure):
    pass
_MV_CC_FILE_ACCESS_PROGRESS_T._fields_ = [
    # CameraParams.h 529
    ('nCompleted', int64_t),
    ('nTotal', int64_t),
    ('nReserved', c_uint * 8),
]
MV_CC_FILE_ACCESS_PROGRESS = _MV_CC_FILE_ACCESS_PROGRESS_T
# CameraParams.h 538
class _MV_TRANSMISSION_TYPE_T(Structure):
    pass
_MV_TRANSMISSION_TYPE_T._fields_ = [
    # CameraParams.h 538
    ('enTransmissionType', MV_GIGE_TRANSMISSION_TYPE),
    ('nDestIp', c_uint),
    ('nDestPort', c_ushort),
    ('nReserved', c_uint * 32),
]
MV_TRANSMISSION_TYPE = _MV_TRANSMISSION_TYPE_T

# \~chinese 动作命令信息    \~english Action Command
class _MV_ACTION_CMD_INFO_T(Structure):
    pass
_MV_ACTION_CMD_INFO_T._fields_ = [
    ('nDeviceKey', c_uint),        # < \~chinese 设备密钥                                     \~english Device key
    ('nGroupKey', c_uint),         # < \~chinese 组键                                          \~english Group key
    ('nGroupMask', c_uint),        # < \~chinese 组掩码                                         \~english Group mask
    ('bActionTimeEnable', c_uint), # < \~chinese 只有设置成1时Action Time才有效，非1时无效         \~english Action time enable
    ('nActionTime', int64_t),      # < \~chinese 预定的时间，和主频有关                             \~english Action time
    ('pBroadcastAddress', STRING), # < \~chinese 广播包地址                                         \~english Broadcast address
    ('nTimeOut', c_uint),          # < \~chinese 等待ACK的超时时间，如果为0表示不需要ACK               \~english Timeout
    ('nReserved', c_uint * 16),    # < \~chinese 预留                                                 \~english Reserved bytes
]
MV_ACTION_CMD_INFO = _MV_ACTION_CMD_INFO_T

# \~chinese 动作命令返回信息    \~english Action Command Result
class _MV_ACTION_CMD_RESULT_T(Structure):
    pass
_MV_ACTION_CMD_RESULT_T._fields_ = [
    ('strDeviceAddress', c_ubyte * 16), # < \~chinese IP配置选项         \~english IP address of the device
    #1.0x0000:success.
    #2.0x8001:Command is not supported by the device.
    #3.0x8013:The device is not synchronized to a master clock to be used as time reference.
    #4.0x8015:A device queue or packet data has overflowed.
    #5.0x8016:The requested scheduled action command was requested at a time that is already past.
    ('nStatus', c_int),                 # < \~chinese 状态码            \~english status
    ('nReserved', c_uint * 4),          # < \~chinese 预留              \~english Reserved bytes
]
MV_ACTION_CMD_RESULT = _MV_ACTION_CMD_RESULT_T

# \~chinese 动作命令返回信息列表    \~english Action Command Result List
class _MV_ACTION_CMD_RESULT_LIST_T(Structure):
    pass
_MV_ACTION_CMD_RESULT_LIST_T._fields_ = [
    ('nNumResults', c_uint),                     # < \~chinese 返回值个数         \~english Num Results
    ('pResults', POINTER(MV_ACTION_CMD_RESULT)), # < \~chinese 动作命令返回信息        \~english action command result list
]
MV_ACTION_CMD_RESULT_LIST = _MV_ACTION_CMD_RESULT_LIST_T

# CameraParams.h 548
class _MV_XML_NODE_FEATURE_(Structure):
    pass
_MV_XML_NODE_FEATURE_._fields_ = [
    # CameraParams.h 548
    ('enType', MV_XML_InterfaceType),
    ('enVisivility', MV_XML_Visibility),
    ('strDescription', c_char * 512),
    ('strDisplayName', c_char * 64),
    ('strName', c_char * 64),
    ('strToolTip', c_char * 512),
    ('nReserved', c_uint * 4),
]
MV_XML_NODE_FEATURE = _MV_XML_NODE_FEATURE_
# CameraParams.h 561
class _MV_XML_NODES_LIST_(Structure):
    pass
_MV_XML_NODES_LIST_._fields_ = [
    # CameraParams.h 561
    ('nNodeNum', c_uint),
    ('stNodes', MV_XML_NODE_FEATURE * 128),
]
MV_XML_NODES_LIST = _MV_XML_NODES_LIST_
# CameraParams.h 569
class _MV_XML_FEATURE_Value_(Structure):
    pass
_MV_XML_FEATURE_Value_._fields_ = [
    # CameraParams.h 569
    ('enType', MV_XML_InterfaceType),
    ('strDescription', c_char * 512),
    ('strDisplayName', c_char * 64),
    ('strName', c_char * 64),
    ('strToolTip', c_char * 512),
    ('nReserved', c_uint * 4),
]
MV_XML_FEATURE_Value = _MV_XML_FEATURE_Value_
# CameraParams.h 579
class _MV_XML_FEATURE_Base_(Structure):
    pass
_MV_XML_FEATURE_Base_._fields_ = [
    # CameraParams.h 579
    ('enAccessMode', MV_XML_AccessMode),
]
MV_XML_FEATURE_Base = _MV_XML_FEATURE_Base_
# CameraParams.h 584
class _MV_XML_FEATURE_Integer_(Structure):
    pass
_MV_XML_FEATURE_Integer_._fields_ = [
    # CameraParams.h 584
    ('strName', c_char * 64),
    ('strDisplayName', c_char * 64),
    ('strDescription', c_char * 512),
    ('strToolTip', c_char * 512),
    ('enVisivility', MV_XML_Visibility),
    ('enAccessMode', MV_XML_AccessMode),
    ('bIsLocked', c_int),
    ('nValue', int64_t),
    ('nMinValue', int64_t),
    ('nMaxValue', int64_t),
    ('nIncrement', int64_t),
    ('nReserved', c_uint * 4),
]
MV_XML_FEATURE_Integer = _MV_XML_FEATURE_Integer_
# CameraParams.h 603
class _MV_XML_FEATURE_Boolean_(Structure):
    pass
_MV_XML_FEATURE_Boolean_._fields_ = [
    # CameraParams.h 603
    ('strName', c_char * 64),
    ('strDisplayName', c_char * 64),
    ('strDescription', c_char * 512),
    ('strToolTip', c_char * 512),
    ('enVisivility', MV_XML_Visibility),
    ('enAccessMode', MV_XML_AccessMode),
    ('bIsLocked', c_int),
    ('bValue', c_bool),
    ('nReserved', c_uint * 4),
]
MV_XML_FEATURE_Boolean = _MV_XML_FEATURE_Boolean_
# CameraParams.h 618
class _MV_XML_FEATURE_Command_(Structure):
    pass
_MV_XML_FEATURE_Command_._fields_ = [
    # CameraParams.h 618
    ('strName', c_char * 64),
    ('strDisplayName', c_char * 64),
    ('strDescription', c_char * 512),
    ('strToolTip', c_char * 512),
    ('enVisivility', MV_XML_Visibility),
    ('enAccessMode', MV_XML_AccessMode),
    ('bIsLocked', c_int),
    ('nReserved', c_uint * 4),
]
MV_XML_FEATURE_Command = _MV_XML_FEATURE_Command_
# CameraParams.h 632
class _MV_XML_FEATURE_Float_(Structure):
    pass
_MV_XML_FEATURE_Float_._fields_ = [
    # CameraParams.h 632
    ('strName', c_char * 64),
    ('strDisplayName', c_char * 64),
    ('strDescription', c_char * 512),
    ('strToolTip', c_char * 512),
    ('enVisivility', MV_XML_Visibility),
    ('enAccessMode', MV_XML_AccessMode),
    ('bIsLocked', c_int),
    ('dfValue', c_double),
    ('dfMinValue', c_double),
    ('dfMaxValue', c_double),
    ('dfIncrement', c_double),
    ('nReserved', c_uint * 4),
]
MV_XML_FEATURE_Float = _MV_XML_FEATURE_Float_
# CameraParams.h 650
class _MV_XML_FEATURE_String_(Structure):
    pass
_MV_XML_FEATURE_String_._fields_ = [
    # CameraParams.h 650
    ('strName', c_char * 64),
    ('strDisplayName', c_char * 64),
    ('strDescription', c_char * 512),
    ('strToolTip', c_char * 512),
    ('enVisivility', MV_XML_Visibility),
    ('enAccessMode', MV_XML_AccessMode),
    ('bIsLocked', c_int),
    ('strValue', c_char * 64),
    ('nReserved', c_uint * 4),
]
MV_XML_FEATURE_String = _MV_XML_FEATURE_String_
# CameraParams.h 665
class _MV_XML_FEATURE_Register_(Structure):
    pass
_MV_XML_FEATURE_Register_._fields_ = [
    # CameraParams.h 665
    ('strName', c_char * 64),
    ('strDisplayName', c_char * 64),
    ('strDescription', c_char * 512),
    ('strToolTip', c_char * 512),
    ('enVisivility', MV_XML_Visibility),
    ('enAccessMode', MV_XML_AccessMode),
    ('bIsLocked', c_int),
    ('nAddrValue', int64_t),
    ('nReserved', c_uint * 4),
]
MV_XML_FEATURE_Register = _MV_XML_FEATURE_Register_
# CameraParams.h 680
class _MV_XML_FEATURE_Category_(Structure):
    pass
_MV_XML_FEATURE_Category_._fields_ = [
    # CameraParams.h 680
    ('strDescription', c_char * 512),
    ('strDisplayName', c_char * 64),
    ('strName', c_char * 64),
    ('strToolTip', c_char * 512),
    ('enVisivility', MV_XML_Visibility),
    ('nReserved', c_uint * 4),
]
MV_XML_FEATURE_Category = _MV_XML_FEATURE_Category_
# CameraParams.h 692
class _MV_XML_FEATURE_EnumEntry_(Structure):
    pass
_MV_XML_FEATURE_EnumEntry_._fields_ = [
    # CameraParams.h 692
    ('strName', c_char * 64),
    ('strDisplayName', c_char * 64),
    ('strDescription', c_char * 512),
    ('strToolTip', c_char * 512),
    ('bIsImplemented', c_int),
    ('nParentsNum', c_int),
    ('stParentsList', MV_XML_NODE_FEATURE * 8),
    ('enVisivility', MV_XML_Visibility),
    ('nValue', int64_t),
    ('enAccessMode', MV_XML_AccessMode),
    ('bIsLocked', c_int),
    ('nReserved', c_int * 8),
]
MV_XML_FEATURE_EnumEntry = _MV_XML_FEATURE_EnumEntry_
# CameraParams.h 711
class _MV_XML_FEATURE_Enumeration_(Structure):
    pass
_MV_XML_FEATURE_Enumeration_._fields_ = [
    # CameraParams.h 711
    ('enVisivility', MV_XML_Visibility),
    ('strDescription', c_char * 512),
    ('strDisplayName', c_char * 64),
    ('strName', c_char * 64),
    ('strToolTip', c_char * 512),
    ('nSymbolicNum', c_int),
    ('strCurrentSymbolic', c_char * 64),
    ('strSymbolic', c_char * 64 * 64),
    ('enAccessMode', MV_XML_AccessMode),
    ('bIsLocked', c_int),
    ('nValue', int64_t),
    ('nReserved', c_uint * 4),
]
MV_XML_FEATURE_Enumeration = _MV_XML_FEATURE_Enumeration_
# CameraParams.h 730
class _MV_XML_FEATURE_Port_(Structure):
    pass
_MV_XML_FEATURE_Port_._fields_ = [
    # CameraParams.h 730
    ('enVisivility', MV_XML_Visibility),
    ('strDescription', c_char * 512),
    ('strDisplayName', c_char * 64),
    ('strName', c_char * 64),
    ('strToolTip', c_char * 512),
    ('enAccessMode', MV_XML_AccessMode),
    ('bIsLocked', c_int),
    ('nReserved', c_uint * 4),
]
MV_XML_FEATURE_Port = _MV_XML_FEATURE_Port_
# CameraParams.h 746
class _MV_XML_CAMERA_FEATURE_(Structure):
    pass
# CameraParams.h 749
class N23_MV_XML_CAMERA_FEATURE_3DOT_1E(Union):
    pass
N23_MV_XML_CAMERA_FEATURE_3DOT_1E._fields_ = [
    # CameraParams.h 749
    ('stIntegerFeature', MV_XML_FEATURE_Integer),
    ('stFloatFeature', MV_XML_FEATURE_Float),
    ('stEnumerationFeature', MV_XML_FEATURE_Enumeration),
    ('stStringFeature', MV_XML_FEATURE_String),
]
_MV_XML_CAMERA_FEATURE_._fields_ = [
    # CameraParams.h 746
    ('enType', MV_XML_InterfaceType),
    ('SpecialFeature', N23_MV_XML_CAMERA_FEATURE_3DOT_1E),
]
MV_XML_CAMERA_FEATURE = _MV_XML_CAMERA_FEATURE_
# CameraParams.h 760
class _MVCC_ENUMVALUE_T(Structure):
    pass
_MVCC_ENUMVALUE_T._fields_ = [
    # CameraParams.h 760
    ('nCurValue', c_uint),
    ('nSupportedNum', c_uint),
    ('nSupportValue', c_uint * 64),
    ('nReserved', c_uint * 4),
]
MVCC_ENUMVALUE = _MVCC_ENUMVALUE_T
# CameraParams.h 769
class _MVCC_INTVALUE_T(Structure):
    pass
_MVCC_INTVALUE_T._fields_ = [
    # CameraParams.h 769
    ('nCurValue', c_uint),
    ('nMax', c_uint),
    ('nMin', c_uint),
    ('nInc', c_uint),
    ('nReserved', c_uint * 4),
]
MVCC_INTVALUE = _MVCC_INTVALUE_T
# CameraParams.h 779
class _MVCC_INTVALUE_EX_T(Structure):
    pass
_MVCC_INTVALUE_EX_T._fields_ = [
    # CameraParams.h 779
    ('nCurValue', int64_t),
    ('nMax', int64_t),
    ('nMin', int64_t),
    ('nInc', int64_t),
    ('nReserved', c_uint * 16),
]
MVCC_INTVALUE_EX = _MVCC_INTVALUE_EX_T
# CameraParams.h 789
class _MVCC_FLOATVALUE_T(Structure):
    pass
_MVCC_FLOATVALUE_T._fields_ = [
    # CameraParams.h 789
    ('fCurValue', c_float),
    ('fMax', c_float),
    ('fMin', c_float),
    ('nReserved', c_uint * 4),
]
MVCC_FLOATVALUE = _MVCC_FLOATVALUE_T
# CameraParams.h 798
class _MVCC_STRINGVALUE_T(Structure):
    pass
_MVCC_STRINGVALUE_T._fields_ = [
    # CameraParams.h 798
    ('chCurValue', c_char * 256),
    ('nMaxLength', int64_t),
    ('nReserved', c_uint * 2),
]
MVCC_STRINGVALUE = _MVCC_STRINGVALUE_T

# values for enumeration '_MV_SORT_METHOD_'
_MV_SORT_METHOD_ = c_int  # enum
MV_SORT_METHOD = _MV_SORT_METHOD_

# values for enumeration '_MV_IMG_ROTATION_ANGLE_'
_MV_IMG_ROTATION_ANGLE_ = c_int  # enum
MV_IMG_ROTATION_ANGLE = _MV_IMG_ROTATION_ANGLE_

# values for enumeration '_MV_IMG_FLIP_TYPE_'
_MV_IMG_FLIP_TYPE_ = c_int  # enum
MV_IMG_FLIP_TYPE = _MV_IMG_FLIP_TYPE_

# values for enumeration '_MV_CC_GAMMA_TYPE_'
_MV_CC_GAMMA_TYPE_ = c_int  # enum
MV_CC_GAMMA_TYPE = _MV_CC_GAMMA_TYPE_

# values for enumeration '_MV_CC_STREAM_EXCEPTION_TYPE_'
_MV_CC_STREAM_EXCEPTION_TYPE_ = c_int  # enum
MV_CC_STREAM_EXCEPTION_TYPE = _MV_CC_STREAM_EXCEPTION_TYPE_

# values for enumeration '_MV_IMAGE_RECONSTRUCTION_METHOD_'
_MV_IMAGE_RECONSTRUCTION_METHOD_ = c_int  # enum
MV_IMAGE_RECONSTRUCTION_METHOD = _MV_IMAGE_RECONSTRUCTION_METHOD_

# \~chinese 图像旋转结构体            \~english Rotate image structure
class _MV_CC_ROTATE_IMAGE_PARAM_T_(Structure):
    pass
_MV_CC_ROTATE_IMAGE_PARAM_T_._fields_ = [
    ('enPixelType', MvGvspPixelType),   # < \~chinese 像素格式              \~english pixel format
    ('nWidth', c_uint),                 # < \~chinese 图像宽                \~english Image Width
    ('nHeight', c_uint),                # < \~chinese 图像高                \~english Image Height
    ('pSrcData', POINTER(c_ubyte)),     # < \~chinese 输入数据缓存           \~english Input data buffer
    ('nSrcDataLen', c_uint),            # < \~chinese 输入数据大小           \~english Input data length
    ('pDstBuf', POINTER(c_ubyte)),      # < \~chinese 输出数据缓存           \~english Output data buffer
    ('nDstBufLen', c_uint),             # < \~chinese输出数据长度            \~english Output data length
    ('nDstBufSize', c_uint),            # < \~chinese  提供的输出缓冲区大小    \~english Provided output buffer size
    ('enRotationAngle', MV_IMG_ROTATION_ANGLE),   # < \~chinese  旋转角度               \~english Rotation angle
    ('nRes', c_uint * 8),               # < \~chinese 保留字节               \~english Reserved bytes
]
MV_CC_ROTATE_IMAGE_PARAM = _MV_CC_ROTATE_IMAGE_PARAM_T_

# \~chinese 图像翻转结构体            \~english Flip image structure
class _MV_CC_FLIP_IMAGE_PARAM_T_(Structure):
    pass
_MV_CC_FLIP_IMAGE_PARAM_T_._fields_ = [
    ('enPixelType', MvGvspPixelType),   # < \~chinese 像素格式              \~english pixel format
    ('nWidth', c_uint),                 # < \~chinese 图像宽                \~english Image Width
    ('nHeight', c_uint),                # < \~chinese 图像高                \~english Image Height
    ('pSrcData', POINTER(c_ubyte)),     # < \~chinese 输入数据缓存           \~english Input data buffer
    ('nSrcDataLen', c_uint),            # < \~chinese 输入数据大小           \~english Input data length
    ('pDstBuf', POINTER(c_ubyte)),      # < \~chinese 输出数据缓存           \~english Output data buffer
    ('nDstBufLen', c_uint),             # < \~chinese输出数据长度            \~english Output data length
    ('nDstBufSize', c_uint),            # < \~chinese  提供的输出缓冲区大小    \~english Provided output buffer size
    ('enFlipType', MV_IMG_FLIP_TYPE),   # < \~chinese  翻转类型              \~english Flip type
    ('nRes', c_uint * 8),               # < \~chinese 保留字节               \~english Reserved bytes
]
MV_CC_FLIP_IMAGE_PARAM = _MV_CC_FLIP_IMAGE_PARAM_T_

# \~chinese Gamma信息结构体           \~english Gamma info structure
class _MV_CC_GAMMA_PARAM_T_(Structure):
    pass
_MV_CC_GAMMA_PARAM_T_._fields_ = [
    ('enGammaType', MV_CC_GAMMA_TYPE),       # < \~chinese Gamma类型              \~english Gamma type
    ('fGammaValue', c_float),                # < \~chinese Gamma值[0.1,4.0]       \~english Gamma value[0.1,4.0]
    ('pGammaCurveBuf', POINTER(c_ubyte)),    # < \~chinese Gamma曲线缓存          \~english Gamma curve buffer
    ('nGammaCurveBufLen', c_uint),           # < \~chinese Gamma曲线长度          \~english Gamma curve buffer size
    ('nRes', c_uint * 8),                    # < \~chinese 保留字节             \~english Reserved bytes
]
MV_CC_GAMMA_PARAM = _MV_CC_GAMMA_PARAM_T_

# \~chinese CCM参数                   \~english CCM param
class _MV_CC_CCM_PARAM_T_(Structure):
    pass
_MV_CC_CCM_PARAM_T_._fields_ = [
    ('bCCMEnable', c_bool),         # < \~chinese 是否启用CCM            \~english CCM enable
    ('nCCMat', c_int * 9),          # < \~chinese CCM矩阵(-8192~8192)    \~english Color correction matrix(-8192~8192)
    ('nRes', c_uint * 8),           # < \~chinese 保留字节             \~english Reserved bytes
]
MV_CC_CCM_PARAM = _MV_CC_CCM_PARAM_T_

# \~chinese CCM参数                   \~english CCM param
class _MV_CC_CCM_PARAM_EX_T_(Structure):
    pass
_MV_CC_CCM_PARAM_EX_T_._fields_ = [
    ('bCCMEnable', c_bool),         # < \~chinese 是否启用CCM            \~english CCM enable
    ('nCCMat', c_int * 9),          # < \~chinese CCM矩阵(-65536~65536)  \~english Color correction matrix(-65536~65536)
    ('nCCMScale', c_uint),
    # < \~chinese 量化系数（2的整数幂,最大65536）    \~english Quantitative scale(Integer power of 2, <= 65536)
    ('nRes', c_uint * 8),           # < \~chinese 保留字节             \~english Reserved bytes
]
MV_CC_CCM_PARAM_EX = _MV_CC_CCM_PARAM_EX_T_

# \~chinese 对比度调节结构体          \~english Contrast structure
class _MV_CC_CONTRAST_PARAM_T_(Structure):
    pass
_MV_CC_CONTRAST_PARAM_T_._fields_ = [
    ('nWidth', c_uint),                 # < \~chinese 图像宽(最小8)         \~english Image Width
    ('nHeight', c_uint),                # < \~chinese 图像高(最小8)         \~english Image Height
    ('pSrcBuf', POINTER(c_ubyte)),      # < \~chinese 输入数据缓存           \~english Input data buffer
    ('nSrcBufLen', c_uint),             # < \~chinese 输入数据大小           \~english Input data length
    ('enPixelType', MvGvspPixelType),   # < \~chinese 像素格式               \~english pixel format
    ('pDstBuf', POINTER(c_ubyte)),      # < \~chinese 输出数据缓存          \~english Output data buffer
    ('nDstBufSize', c_uint),            # < \~chinese提供的输出缓冲区大小     \~english Provided output buffer size
    ('nDstBufLen', c_uint),            # < \~chinese  输出数据长度           \~english Output data length
    ('nContrastFactor', c_uint),       # < \~chinese  对比度值，[1,10000]    \~english Contrast factor,[1,10000]
    ('nRes', c_uint * 8),                 # < \~chinese 保留字节             \~english Reserved bytes
]
MV_CC_CONTRAST_PARAM_T = _MV_CC_CONTRAST_PARAM_T_

# \~chinese 枚举类型条目          \~english Enumeration Entry
class _MVCC_ENUMENTRY_T(Structure):
    pass
_MVCC_ENUMENTRY_T._fields_ = [
    ('nValue', c_uint),                             # < \~chinese 指定值               \~english Value
    ('chSymbolic', c_char * MV_MAX_SYMBOLIC_LEN),  # < \~chinese 指定值对应的符号       \~english Symbolic

    ('nReserved', c_uint * 4),                      # < \~chinese 预留                 \~english Reserved bytes
]
MVCC_ENUMENTRY = _MVCC_ENUMENTRY_T

# \~chinese 辅助线颜色                \~english Color of Auxiliary Line
class _MVCC_COLORF(Structure):
    pass
_MVCC_COLORF._fields_ = [
    ('fR', c_float),
    # < \~chinese 红色，根据像素颜色的相对深度，范围为[0.0 , 1.0]，代表着[0, 255]的颜色深度   \~english Red，Range[0.0, 1.0]
    ('fG', c_float),
    # < \~chinese 绿色，根据像素颜色的相对深度，范围为[0.0 , 1.0]，代表着[0, 255]的颜色深度   \~english Green，Range[0.0, 1.0]
    ('fB', c_float),
    # < \~chinese 蓝色，根据像素颜色的相对深度，范围为[0.0 , 1.0]，代表着[0, 255]的颜色深度   \~english Blue，Range[0.0, 1.0]
    ('fAlpha', c_float),
    # < \~chinese 透明度，根据像素颜色的相对透明度，范围为[0.0 , 1.0] (此参数功能暂不支持)    \~english Alpha，Range[0.0, 1.0](Not Support)
    ('nReserved', c_uint * 4),     # < \~chinese 保留字节                            \~english Reserved bytes
]
MVCC_COLORF = _MVCC_COLORF

# \~chinese 自定义点                    \~english Point defined
class _MVCC_POINTF(Structure):
    pass
_MVCC_POINTF._fields_ = [
    ('fX', c_float),
    # < \~chinese 该点距离图像左边缘距离，根据图像的相对位置，范围为[0.0 , 1.0]   \~english Distance From Left，Range[0.0, 1.0]
    ('fY', c_float),
    # < \~chinese 该点距离图像上边缘距离，根据图像的相对位置，范围为[0.0 , 1.0]   \~english Distance From Top，Range[0.0, 1.0]
    ('nReserved', c_uint * 4),     # < \~chinese 保留字节                 \~english Reserved bytes
]
MVCC_POINTF = _MVCC_POINTF

# \~chinese 矩形框区域信息            \~english Rect Area Info
class _MVCC_RECT_INFO(Structure):
    pass
_MVCC_RECT_INFO._fields_ = [
    ('fTop', c_float),
    # < \~chinese 矩形上边缘距离图像上边缘的距离，根据图像的相对位置，范围为[0.0 , 1.0]   \~english Distance From Top，Range[0, 1.0]
    ('fBottom', c_float),
    # < \~chinese 矩形下边缘距离图像下边缘的距离，根据图像的相对位置，范围为[0.0 , 1.0]   \~english Distance From Bottom，Range[0, 1.0]
    ('fLeft', c_float),
    # < \~chinese 矩形左边缘距离图像左边缘的距离，根据图像的相对位置，范围为[0.0 , 1.0]   \~english Distance From Left，Range[0, 1.0]
    ('fRight', c_float),
    # < \~chinese 矩形右边缘距离图像右边缘的距离，根据图像的相对位置，范围为[0.0 , 1.0]   \~english Distance From Right，Range[0, 1.0]
    ('stColor', MVCC_COLORF),      # < \~chinese 辅助线颜色信息                \~english Color of Auxiliary Line
    ('nLineWidth', c_uint),        # < \~chinese 辅助线宽度，宽度只能是1或2      \~english Width of Auxiliary Line, width is 1 or 2
    ('nReserved', c_uint * 4),     # < \~chinese 保留字节                     \~english Reserved bytes
]
MVCC_RECT_INFO = _MVCC_RECT_INFO

# \~chinese 圆形框区域信息            \~english Circle Area Info
class _MVCC_CIRCLE_INFO(Structure):
    pass
_MVCC_CIRCLE_INFO._fields_ = [
    ('stCenterPoint', MVCC_POINTF),  # < \~chinese 圆心信息                   \~english Circle Point Info
    ('fR1', c_float),
    # < \~chinese 宽向半径，根据图像的相对位置[0, 1.0]，半径与圆心的位置有关，需保证画出的圆在显示框范围之内，否则报错  \~english Width Radius, Range[0, 1.0]
    ('fR2', c_float),
    # < \~chinese高向半径，根据图像的相对位置[0, 1.0]，半径与圆心的位置有关，需保证画出的圆在显示框范围之内，否则报错  \~english Height Radius, Range[0, 1.0]
    ('stColor', MVCC_COLORF),      # < \~chinese 辅助线颜色信息                \~english Color of Auxiliary Line
    ('nLineWidth', c_uint),        # < \~chinese 辅助线宽度，宽度只能是1或2      \~english Width of Auxiliary Line, width is 1 or 2
    ('nReserved', c_uint * 4),     # < \~chinese 保留字节                     \~english Reserved bytes
]
MVCC_CIRCLE_INFO = _MVCC_CIRCLE_INFO

# \~chinese 线条辅助线信息    \~english Linear Auxiliary Line Info
class _MVCC_LINES_INFO(Structure):
    pass
_MVCC_LINES_INFO._fields_ = [
    ('stStartPoint', MVCC_POINTF), # < \~chinese 线条辅助线的起始点坐标         \~english The Start Point of Auxiliary Line
    ('stEndPoint', MVCC_POINTF),   # < \~chinese线条辅助线的终点坐标            \~english The End Point of Auxiliary Line
    ('stColor', MVCC_COLORF),      # < \~chinese 辅助线颜色信息                \~english Color of Auxiliary Line
    ('nLineWidth', c_uint),        # < \~chinese 辅助线宽度，宽度只能是1或2      \~english Width of Auxiliary Line, width is 1 or 2
    ('nReserved', c_uint * 4),     # < \~chinese 保留字节             \~english Reserved bytes
]
MVCC_LINES_INFO = _MVCC_LINES_INFO

# \~chinese 图像重构后的图像列表      \~english List of images after image reconstruction
class _MV_OUTPUT_IMAGE_INFO_(Structure):
    pass
_MV_OUTPUT_IMAGE_INFO_._fields_ = [
    ('nWidth', c_uint),                 # < \~chinese 图像宽                \~english Image Width
    ('nHeight', c_uint),                # < \~chinese 图像高                \~english Image Height
    ('enPixelType', MvGvspPixelType),   # < \~chinese 像素格式               \~english pixel format
    ('pBuf', POINTER(c_ubyte)),      # < \~chinese 输出数据缓存          \~english Output data buffer
    ('nBufLen', c_uint),             # < \~chinese 输出数据长度          \~english Output data length
    ('nBufSize', c_uint),            # < \~chinese  提供的输出缓冲区大小  \~english Provided output buffer size
    ('nRes', c_uint * 8),                 # < \~chinese 保留字节             \~english Reserved bytes
]
MV_OUTPUT_IMAGE_INFO = _MV_OUTPUT_IMAGE_INFO_

# \~chinese 重构图像参数信息      \~english Restructure image parameters
class _MV_RECONSTRUCT_IMAGE_PARAM_(Structure):
    pass
_MV_RECONSTRUCT_IMAGE_PARAM_._fields_ = [
    ('nWidth', c_uint),                 # < \~chinese 图像宽                \~english Image Width
    ('nHeight', c_uint),                # < \~chinese 图像高                \~english Image Height
    ('enPixelType', MvGvspPixelType),   # < \~chinese 像素格式               \~english pixel format
    ('pSrcData', POINTER(c_ubyte)),      # < \~chinese 输入数据缓存           \~english input data buffer
    ('nSrcDataLen', c_uint),             # < \~chinese 输入数据大小            \~english input data size
    ('nExposureNum', c_uint),            # < \~chinese  曝光个数(1-8]     \~english Exposure number
    ('enReconstructMethod', MV_IMAGE_RECONSTRUCTION_METHOD),   # < \~chinese 图像重构方式      \~english Image restructuring method
    ('stDstBufList', MV_OUTPUT_IMAGE_INFO * MV_MAX_SPLIT_NUM),  # < \~chinese 输出数据缓存信息  \~english Output data info
    ('nRes', c_uint * 4),                 # < \~chinese 保留字节             \~english Reserved bytes
]
MV_RECONSTRUCT_IMAGE_PARAM = _MV_RECONSTRUCT_IMAGE_PARAM_

# \~chinese 文件存取                  \~english File Access
class _MV_CC_FILE_ACCESS_E(Structure):
    pass
_MV_CC_FILE_ACCESS_E._fields_ = [
    ('pUserFileBuf', POINTER(c_char)),  # < \~chinese 用户文件数据        \~english User file data
    ('pFileBufSize', c_uint),  # < \~chinese 用户数据缓存大小       \~english data buffer size
    ('pFileBufLen', c_uint),   # < \~chinese 用户数据缓存长度       \~english data buffer len
    ('pDevFileName', STRING),           # < \~chinese 设备文件名          \~english Device file name
    ('nReserved', c_uint * 32),         # < \~chinese 保留字节            \~english Reserved bytes
]
MV_CC_FILE_ACCESS_EX = _MV_CC_FILE_ACCESS_E
__all__ = ['_MV_ALL_MATCH_INFO_', '_MV_XML_FEATURE_Integer_',
           'MV_CC_FILE_ACCESS_PROGRESS',
           'N19_MV_CC_DEVICE_INFO_3DOT_0E',
           'MV_CAM_EXPOSURE_AUTO_MODE', 'PixelType_Gvsp_BayerRG8',
           'MV_CAM_GAIN_MODE',
           'MV_GIGE_TRANSTYPE_UNICAST_WITHOUT_RECV',
           'PixelType_Gvsp_BayerGB12_Packed',
           'MV_TRIGGER_SOURCE_LINE0', 'MV_TRIGGER_SOURCE_LINE1',
           'MV_TRIGGER_SOURCE_LINE2', 'MV_TRIGGER_SOURCE_LINE3',
           'AM_CycleDetect', 'PixelType_Gvsp_YCBCR422_8',
           'IFT_IFloat', 'MV_TRANSMISSION_TYPE',
           '_MV_XML_FEATURE_Command_', '_MV_XML_FEATURE_String_',
           '_MV_CAM_TRIGGER_SOURCE_',
           'PixelType_Gvsp_COORD3D_DEPTH_PLUS_MASK',
           'PixelType_Gvsp_RGB10V1_Packed',
           'PixelType_Gvsp_RGB10_Packed',
           'PixelType_Gvsp_RGB8_Planar', 'AM_RO', 'IFT_IPort',
           'uint_least16_t', '_MV_FRAME_OUT_INFO_EX_',
           '_MV_TRANSMISSION_TYPE_T', 'MV_SAVE_IMAGE_PARAM_EX',
           'AM_RW', 'MV_XML_InterfaceType', '_MV_XML_CAMERA_FEATURE_',
           'intptr_t', 'uint_least64_t', 'V_Guru',
           '_MV_CAM_TRIGGER_MODE_', 'MV_CAM_EXPOSURE_MODE',
           'int_least32_t', 'MV_GIGE_TRANSTYPE_SUBNETBROADCAST',
           '_MV_XML_FEATURE_Boolean_',
           'MV_BALANCEWHITE_AUTO_CONTINUOUS', 'MV_XML_NODE_FEATURE',
           '_MV_FRAME_OUT_INFO_', 'MV_ALL_MATCH_INFO',
           '_MV_XML_FEATURE_EnumEntry_', '_MV_PIXEL_CONVERT_PARAM_T_',
           'PixelType_Gvsp_RGB16_Packed',
           'PixelType_Gvsp_RGBA8_Packed',
           'PixelType_Gvsp_RGB8_Packed', 'MV_ACQ_MODE_SINGLE',
           'MV_TRIGGER_MODE_ON', '_MV_XML_FEATURE_Base_',
           'PixelType_Gvsp_Mono8_Signed', 'int_least16_t',
           'MV_GIGE_TRANSTYPE_LIMITEDBROADCAST', 'int_fast32_t',
           '_MV_CAM_GAIN_MODE_', 'uint_fast16_t',
           '_MV_DISPLAY_FRAME_INFO_', 'IFT_ICommand',
           'PixelType_Gvsp_BayerBG10_Packed',
           '_MV_CAM_ACQUISITION_MODE_',
           'PixelType_Gvsp_YCBCR709_422_8_CBYCRY', 'V_Beginner',
           'PixelType_Gvsp_BayerBG16',
           'MV_GIGE_TRANSTYPE_MULTICAST_WITHOUT_RECV',
           'MVCC_INTVALUE', '_MV_XML_FEATURE_Port_',
           '_MV_GIGE_TRANSMISSION_TYPE_', 'MV_GIGE_TRANSMISSION_TYPE',
           'PixelType_Gvsp_YUV411_Packed',
           '_MV_XML_FEATURE_Register_', 'MV_EXPOSURE_MODE_TIMED',
           'intmax_t', 'PixelType_Gvsp_BayerBG12_Packed', 'int16_t',
           'MV_DISPLAY_FRAME_INFO', 'MV_XML_FEATURE_Integer',
           '_MV_CC_FILE_ACCESS_PROGRESS_T', 'MV_XML_Visibility',
           'IFT_IEnumEntry', 'int_fast64_t',
           'PixelType_Gvsp_BayerRG12', 'PixelType_Gvsp_BayerRG10',
           'MV_XML_AccessMode', 'V_Expert', 'MV_GAIN_MODE_ONCE',
           'IFT_IInteger', 'PixelType_Gvsp_YCBCR709_411_8_CBYYCRYY',
           'MV_CAM_BALANCEWHITE_AUTO', 'int_least8_t', 'IFT_IBase',
           'MV_XML_NODES_LIST', 'MV_TRIGGER_MODE_OFF', 'MV_Image_Bmp',
           'MV_XML_FEATURE_String', 'MV_CC_FILE_ACCESS',
           '_MV_CAM_EXPOSURE_AUTO_MODE_',
           'PixelType_Gvsp_Coord3D_AC32f', 'uint_least8_t',
           'PixelType_Gvsp_BayerRG12_Packed',
           '_MV_XML_FEATURE_Float_', '_MV_XML_NODE_FEATURE_',
           'MV_XML_FEATURE_Float', 'PixelType_Gvsp_BGR12_Packed',
           'PixelType_Gvsp_YUV422_Packed', 'MV_SAVE_IMAGE_PARAM',
           'MV_EVENT_OUT_INFO', 'IFT_IEnumeration', 'uint64_t',
           'uint8_t', 'PixelType_Gvsp_RGB12_Planar', 'V_Undefined',
           '_MVCC_STRINGVALUE_T', 'PixelType_Gvsp_YCBCR709_422_8',
           'MV_CAM_TRIGGER_MODE', 'PixelType_Gvsp_BayerRG10_Packed',
           'N23_MV_XML_CAMERA_FEATURE_3DOT_1E', 'uint16_t',
           'uint_fast8_t', '_MV_SAVE_IMAGE_PARAM_T_',
           'PixelType_Gvsp_BGR8_Packed', '_MVCC_ENUMVALUE_T',
           '_MV_MATCH_INFO_USB_DETECT_', 'MV_XML_FEATURE_Category',
           'PixelType_Gvsp_Jpeg', 'int32_t',
           'PixelType_Gvsp_BayerGR10_Packed',
           'MV_XML_FEATURE_EnumEntry', '_MV_CC_DEVICE_INFO_',
           'PixelType_Gvsp_BayerBG12', 'PixelType_Gvsp_BayerBG10',
           'IFT_IBoolean', 'PixelType_Gvsp_Mono12',
           'MV_MATCH_INFO_USB_DETECT', 'PixelType_Gvsp_RGB16_Planar',
           'MVCC_ENUMVALUE', 'IFT_IString',
           'PixelType_Gvsp_BayerRG16', '_MV_XML_FEATURE_Value_',
           'MV_ACQ_MODE_CONTINUOUS',
           'MV_TRIGGER_SOURCE_FrequencyConverter',
           'PixelType_Gvsp_Mono4p', 'MV_TRIGGER_SOURCE_COUNTER0',
           'MV_GAIN_MODE_OFF', 'MV_Image_Png',
           '_MV_CC_DEVICE_INFO_LIST_', 'MV_GIGE_DEVICE_INFO',
           '_MV_SAVE_IMAGE_PARAM_T_EX_', 'PixelType_Gvsp_Mono8',
           'uint_least32_t', 'PixelType_Gvsp_BayerGR16',
           'MV_FRAME_OUT_INFO', 'PixelType_Gvsp_BayerGR10',
           'PixelType_Gvsp_BGRA8_Packed', 'PixelType_Gvsp_BayerGR12',
           '_MVCC_INTVALUE_EX_T', 'uintptr_t',
           'PixelType_Gvsp_Mono12_Packed', 'MVCC_FLOATVALUE',
           'MV_GIGE_TRANSTYPE_CAMERADEFINED', '_MV_XML_NODES_LIST_',
           'MV_NETTRANS_INFO', 'IFT_IRegister', 'AM_NA',
           'MV_GIGE_TRANSTYPE_UNICAST', 'int8_t',
           '_MV_GIGE_DEVICE_INFO_', 'IFT_IValue', 'IFT_ICategory',
           'int_fast8_t', 'PixelType_Gvsp_YCBCR709_8_CBYCR',
           'MV_XML_FEATURE_Enumeration', 'MV_GAMMA_SELECTOR_SRGB',
           'PixelType_Gvsp_YCBCR601_422_8',
           'PixelType_Gvsp_YCBCR411_8_CBYYCRYY', 'int_least64_t',
           'MV_EXPOSURE_AUTO_MODE_OFF', 'MV_CC_PIXEL_CONVERT_PARAM',
           'MV_EXPOSURE_AUTO_MODE_CONTINUOUS',
           'MV_CAM_ACQUISITION_MODE', '_MVCC_INTVALUE_T',
           'MV_XML_FEATURE_Value', 'AM_Undefined',
           'MV_MATCH_INFO_NET_DETECT', 'PixelType_Gvsp_Undefined',
           '_MV_CC_FILE_ACCESS_T', 'AM_NI',
           'PixelType_Gvsp_BayerGR12_Packed', 'V_Invisible',
           'PixelType_Gvsp_YCBCR601_411_8_CBYYCRYY',
           'PixelType_Gvsp_RGB10_Planar', 'MV_CAM_GAMMA_SELECTOR',
           'MV_TRIGGER_SOURCE_SOFTWARE', 'PixelType_Gvsp_BayerGB16',
           'MV_BALANCEWHITE_AUTO_ONCE', 'PixelType_Gvsp_BayerGB10',
           'uintmax_t', 'PixelType_Gvsp_BayerGB12', 'int_fast16_t',
           '_MV_CAM_EXPOSURE_MODE_', 'MV_Image_Tif',
           'PixelType_Gvsp_BGR565_Packed', 'MV_BALANCEWHITE_AUTO_OFF',
           'int64_t', 'MV_Image_Undefined', '_MV_NETTRANS_INFO_',
           'MV_GAIN_MODE_CONTINUOUS', 'PixelType_Gvsp_Mono1p',
           'uint_fast32_t', 'MV_CAM_TRIGGER_SOURCE',
           'PixelType_Gvsp_YUV444_Packed', 'MV_Image_Jpeg',
           '_MVCC_FLOATVALUE_T', 'MV_XML_FEATURE_Port',
           'PixelType_Gvsp_YUV422_YUYV_Packed',
           'MV_FRAME_OUT_INFO_EX', '_MV_IMAGE_BASIC_INFO_',
           '_MV_CAM_BALANCEWHITE_AUTO_', 'MV_XML_FEATURE_Base',
           '_MV_USB3_DEVICE_INFO_', 'PixelType_Gvsp_BayerBG8',
           'MVCC_INTVALUE_EX', 'MV_XML_FEATURE_Register', 'AM_WO',
           'MV_GIGE_TRANSTYPE_UNICAST_DEFINED_PORT',
           '_MV_XML_FEATURE_Enumeration_',
           '_MV_MATCH_INFO_NET_DETECT_', 'MV_SAVE_IAMGE_TYPE',
           'MV_EXPOSURE_AUTO_MODE_ONCE',
           'PixelType_Gvsp_BGR10_Packed',
           'PixelType_Gvsp_BayerGB10_Packed',
           'PixelType_Gvsp_Coord3D_ABC32f_Planar',
           'MV_GIGE_TRANSTYPE_MULTICAST', 'MV_XML_CAMERA_FEATURE',
           'PixelType_Gvsp_Coord3D_ABC32f', 'MVCC_STRINGVALUE',
           'MV_CC_DEVICE_INFO', 'PixelType_Gvsp_YCBCR422_8_CBYCRY',
           'PixelType_Gvsp_RGB12_Packed', 'PixelType_Gvsp_BayerGR8',
           'MvGvspPixelType', 'PixelType_Gvsp_Mono10',
           'MV_IMAGE_BASIC_INFO', 'PixelType_Gvsp_Mono16',
           'PixelType_Gvsp_Mono2p', 'PixelType_Gvsp_Mono14',
           'PixelType_Gvsp_RGB10V2_Packed', 'MV_CC_DEVICE_INFO_LIST',
           'PixelType_Gvsp_RGB12V1_Packed',
           'PixelType_Gvsp_Mono10_Packed', 'uint_fast64_t',
           'PixelType_Gvsp_YCBCR601_8_CBYCR',
           'PixelType_Gvsp_BayerGB8', '_MV_XML_FEATURE_Category_',
           'MV_PointCloudFile_Undefined','MV_EXPOSURE_MODE_TRIGGER_WIDTH',
           'PixelType_Gvsp_YCBCR8_CBYCR', 'MV_XML_FEATURE_Boolean',
           'MV_GAMMA_SELECTOR_USER','PixelType_Gvsp_RGB565_Packed',
           'uint32_t','MV_XML_FEATURE_Command',
           '_MV_CAM_GAMMA_SELECTOR_','MV_ACQ_MODE_MUTLI',
           'PixelType_Gvsp_YCBCR601_422_8_CBYCRY',
           'MV_USB3_DEVICE_INFO','_MV_EVENT_OUT_INFO_',
           'MV_GrabStrategy_UpcomingImage','MV_GrabStrategy_LatestImages',
           'MV_GrabStrategy_LatestImagesOnly','MV_PointCloudFile_OBJ',
           'MV_PointCloudFile_CSV','MV_PointCloudFile_PLY',
           'MV_FormatType_Undefined','MV_GrabStrategy_OneByOne',
           'MV_FormatType_AVI','SortMethod_SerialNumber',
           'SortMethod_UserID','SortMethod_CurrentIP_ASC',
           'SortMethod_CurrentIP_DESC','MV_IMAGE_ROTATE_90',
           'MV_IMAGE_ROTATE_180','MV_IMAGE_ROTATE_270',
           'MV_FLIP_VERTICAL','MV_FLIP_HORIZONTAL',
           'MV_CC_GAMMA_TYPE_NONE','MV_CC_GAMMA_TYPE_VALUE',
           'MV_CC_GAMMA_TYPE_USER_CURVE','MV_CC_GAMMA_TYPE_LRGB2SRGB',
           'MV_CC_GAMMA_TYPE_SRGB2LRGB','MV_CC_STREAM_EXCEPTION_ABNORMAL_IMAGE',
           'MV_CC_STREAM_EXCEPTION_LIST_OVERFLOW','MV_CC_STREAM_EXCEPTION_LIST_EMPTY',
           'MV_CC_STREAM_EXCEPTION_RECONNECTION','MV_CC_STREAM_EXCEPTION_DISCONNECTED',
           'MV_CC_STREAM_EXCEPTION_DEVICE','MV_SPLIT_BY_LINE',
           'MV_CamL_DEV_INFO','_MV_CamL_DEV_INFO_',
           'MV_GENTL_IF_INFO','_MV_GENTL_IF_INFO_',
           'MV_GENTL_IF_INFO_LIST','_MV_GENTL_IF_INFO_LIST_',
           'MV_GENTL_DEV_INFO','_MV_GENTL_DEV_INFO_',
           'MV_GENTL_DEV_INFO_LIST','_MV_GENTL_DEV_INFO_LIST_',
           'MV_CHUNK_DATA_CONTENT','_MV_CHUNK_DATA_CONTENT_',
           'N22_MV_FRAME_OUT_INFO_EX_3DOT_1E','MV_DISPLAY_FRAME_INFO_EX', 
           '_MV_DISPLAY_FRAME_INFO_EX_','_MV_FRAME_OUT_',
           '_MV_GRAB_STRATEGY_','MV_GRAB_STRATEGY','MV_SAVE_POINT_CLOUD_FILE_TYPE',
           'MV_SAVE_POINT_CLOUD_PARAM','_MV_SAVE_POINT_CLOUD_PARAM_',
           'MV_FRAME_OUT','MV_RECORD_FORMAT_TYPE','_MV_RECORD_FORMAT_TYPE_',
           'MV_CC_RECORD_PARAM','_MV_CC_RECORD_PARAM_T_',
           'MV_CC_INPUT_FRAME_INFO','_MV_CC_INPUT_FRAME_INFO_T_',
           'MV_ACTION_CMD_INFO','_MV_ACTION_CMD_INFO_T',
           'MV_ACTION_CMD_RESULT','_MV_ACTION_CMD_RESULT_T',
           'MV_ACTION_CMD_RESULT_LIST','_MV_ACTION_CMD_RESULT_LIST_T',
           'MV_SORT_METHOD','_MV_SORT_METHOD_',
           '_MV_IMG_ROTATION_ANGLE_','MV_IMG_ROTATION_ANGLE',
           '_MV_IMG_FLIP_TYPE_','MV_IMG_FLIP_TYPE',
           '_MV_CC_GAMMA_TYPE_','MV_CC_GAMMA_TYPE',
           'MV_CC_STREAM_EXCEPTION_TYPE','_MV_CC_STREAM_EXCEPTION_TYPE_',
           '_MV_IMAGE_RECONSTRUCTION_METHOD_','MV_IMAGE_RECONSTRUCTION_METHOD',
           'MV_CC_ROTATE_IMAGE_PARAM','_MV_CC_ROTATE_IMAGE_PARAM_T_',
           'MV_CC_FLIP_IMAGE_PARAM','_MV_CC_FLIP_IMAGE_PARAM_T_',
           'MV_CC_GAMMA_PARAM','_MV_CC_GAMMA_PARAM_T_',
           'MV_CC_CCM_PARAM','_MV_CC_CCM_PARAM_T_',
           'MV_CC_CCM_PARAM_EX','_MV_CC_CCM_PARAM_EX_T_',
           'MV_CC_CONTRAST_PARAM_T','_MV_CC_CONTRAST_PARAM_T_',
           'MVCC_ENUMENTRY','_MVCC_ENUMENTRY_T',
           'MVCC_COLORF','_MVCC_COLORF',
           'MVCC_POINTF','_MVCC_POINTF',
           'MVCC_RECT_INFO','_MVCC_RECT_INFO',
           'MVCC_CIRCLE_INFO','_MVCC_CIRCLE_INFO',
           'MVCC_LINES_INFO','_MVCC_LINES_INFO',
           'MV_OUTPUT_IMAGE_INFO','_MV_OUTPUT_IMAGE_INFO_',
           'MV_RECONSTRUCT_IMAGE_PARAM','_MV_RECONSTRUCT_IMAGE_PARAM_',
           'MV_CC_FILE_ACCESS_EX','_MV_CC_FILE_ACCESS_E']

