Demo: MultiCast.cpp
	g++ -g -o MultiCast MultiCast.cpp -I../../../include -Wl,-rpath=$(MVCAM_COMMON_RUNENV)/aarch64 -L$(MVCAM_COMMON_RUNENV)/aarch64 -lMvCameraControl -lpthread 
	

clean:
	rm MultiCast -rf
