Demo: ChunkData.cpp
	g++ -g -o ChunkData ChunkData.cpp -I../../../include -Wl,-rpath=$(MVCAM_COMMON_RUNENV)/aarch64 -L$(MVCAM_COMMON_RUNENV)/aarch64 -lMvCameraControl -lpthread
	

clean:
	rm ChunkData -rf
