Demo: InterfaceDemo.cpp
	g++ -g -o InterfaceDemo InterfaceDemo.cpp -I../../../include -Wl,-rpath=$(MVCAM_COMMON_RUNENV)/64 -L$(MVCAM_COMMON_RUNENV)/64 -lMvCameraControl -lpthread
	

clean:
	rm InterfaceDemo -rf
